### ISSUE TITLE
New Version of Topological Navigation

### ISSUE THREAD

**Issue by Jailander** [LCAS/topological_navigation#32]
We want to release a new improved version of topological navigation, that has the following improvements over the current version:

- [x] New map format that can handle all these new features (#35 )
- [x] Edge actions don't have to be **`move_base`** [type](http://docs.ros.org/en/noetic/api/move_base_msgs/html/action/MoveBase.html) anymore (#36 )
- [x] Edge actions can be reconfigured depending on the edge definition (#37 )
- [x] Define recovery strategy for each edge (for example, how many retries for an action on each edge or wether to replan, execute recovery behaviours or cancel on fail)
- [x] Preconditions for edge transitions (for example if the robot has to be at the exact waypoint before triggering the next action)
- [x] Backwards compatibility must be guaranteed 
- [x] Maps can either be hosted in the **MongoDB** or directly into files (#34 )
- [x] Multi-robot capabilities we want the framework to be better prepared for multi-robot systems for example: 
- [x] Handling Hetereogeneous robots types (i.e. some robots might be able to access routes that others can't but still need to be within the same topological framework) (#33 )
- [x] Handling fleet route collisions

**Comment by adambinch** [comment]
Done
